### ISSUE TITLE
Dates for courses are displayed as "invalid date"

### ISSUE THREAD

**Issue by doublegulptank** [Apexal/late#575] opened 2020-01-17 05:10 UTC
**Describe the bug**
In the Dashboard and "Today's Agenda" tab, the dates for courses are displayed as "invalid date", despite being placed correctly in the calendar.
This also prevents you from using the "start of class" and "end of class" buttons when setting a due date for assignments.

**Expected behavior**
Show a date for each course.

**Screenshots**
Dashboard:
https://imgur.com/a/Z6A1xUZ
Calendar:
![image](https://user-images.githubusercontent.com/43162890/72585790-630d1e80-38bd-11ea-84b1-94d44224c2d4.png)
Assignment:
![image](https://user-images.githubusercontent.com/43162890/72585870-a6678d00-38bd-11ea-9cdb-77f449671a10.png)

**Device**
Google Chrome, Windows 10 Pro, latest updates

**Comment by Apexal** [comment] 2020-01-17 15:00
This was caused by updates I made over break! It is fixed now and is being pushed to the site.

**Closed as completed by Apexal** 2020-01-17 15:00 UTC
Labels: Type: Bug, Priority: High, Area: Front End, Difficulty: Easy
